management:
  endpoint:
    health:
      show-components: always

server:
  port: ${SERVER_PORT:8080}


spring:
  data:
    arangodb:
      database: ${ARANGO_DATABASE:scs}
      hosts: ${ARANGO_HOSTS}


scs:
  backend:
    cluster:
      positions: ${SCS_CLUSTER_POSITIONS}
      name: ${SCS_CLUSTER_NAME}