version: '3.7'
services:
  cdev-arango-db-1:
    deploy:
      resources:
        limits:
          memory: 250M
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    ports:
      - "27001:8529"
    volumes:
      - arangodb_data_container_1:/var/lib/arangodb3
      - arangodb_apps_data_container_1:/var/lib/arangodb3-apps
    networks:
      cdev-network:


  cdev-arango-db-2:
    deploy:
      resources:
        limits:
          memory: 250M
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    ports:
      - "27002:8529"
    volumes:
      - arangodb_data_container_2:/var/lib/arangodb3
      - arangodb_apps_data_container_2:/var/lib/arangodb3-apps
    networks:
      cdev-network:


  cdev-arango-db-3:
    deploy:
      resources:
        limits:
          memory: 250M
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    ports:
      - "27003:8529"
    volumes:
      - arangodb_data_container_3:/var/lib/arangodb3
      - arangodb_apps_data_container_3:/var/lib/arangodb3-apps
    networks:
      cdev-network:



  cdev-backend-1-1:
    deploy:
      resources:
        limits:
          memory: 100M
    image: netcracker/scs-backend:latest
    environment:
      ARANGO_HOSTS: cdev-arango-db-1:8529
      SCS_SHARD_ID: 101
      SCS_CLUSTER_MODEL: data/dolgoprudnii.yaml
      SCS_CLUSTER_POSITIONS: >-
        55.8974:37.5070 55.9066:37.5008 55.9072:37.4839 55.9130:37.4824 55.9311:37.4884
        55.9607:37.4872 55.9645:37.48 55.9557:37.467 55.9574:37.4589 55.9669:37.4672
        55.9701:37.4574 55.9734:37.4549 55.9756:37.4575 55.9736:37.4716 55.975:37.4721
        55.979:37.4668 55.9878:37.4693 55.9932:37.4793 55.996:37.4934 55.9905:37.5108
        55.9869:37.5139 55.9863:37.5189 55.9841:37.5175 55.983:37.524 55.9792:37.5241
        55.975:37.5239 55.9688:37.5312 55.9641:37.533 55.9574:37.5339 55.9569:37.5233
        55.9542:37.5248 55.9508:37.5316 55.9473:37.5289 55.944:37.5342 55.94192:37.51924
        55.9077:37.5363 55.9056:37.5262 55.8974:37.5070
      SCS_CLUSTER_NAME: "Долгопрудный"
    ports:
      - "27011:8080"
    depends_on:
      - cdev-arango-db-1
    networks:
      cdev-network:

  cdev-backend-1-2:
    deploy:
      resources:
        limits:
          memory: 100M
    image: netcracker/scs-backend:latest
    environment:
      ARANGO_HOSTS: cdev-arango-db-1:8529
      SCS_SHARD_ID: 101
      SCS_CLUSTER_MODEL: data/dolgoprudnii.yaml
      SCS_CLUSTER_POSITIONS: >-
        55.8974:37.5070 55.9066:37.5008 55.9072:37.4839 55.9130:37.4824 55.9311:37.4884
        55.9607:37.4872 55.9645:37.48 55.9557:37.467 55.9574:37.4589 55.9669:37.4672
        55.9701:37.4574 55.9734:37.4549 55.9756:37.4575 55.9736:37.4716 55.975:37.4721
        55.979:37.4668 55.9878:37.4693 55.9932:37.4793 55.996:37.4934 55.9905:37.5108
        55.9869:37.5139 55.9863:37.5189 55.9841:37.5175 55.983:37.524 55.9792:37.5241
        55.975:37.5239 55.9688:37.5312 55.9641:37.533 55.9574:37.5339 55.9569:37.5233
        55.9542:37.5248 55.9508:37.5316 55.9473:37.5289 55.944:37.5342 55.94192:37.51924
        55.9077:37.5363 55.9056:37.5262 55.8974:37.5070
      SCS_CLUSTER_NAME: "Долгопрудный"
    ports:
      - "27012:8080"
    depends_on:
      - cdev-arango-db-1
    networks:
      cdev-network:


  cdev-backend-2-1:
    deploy:
      resources:
        limits:
          memory: 100M
    image: netcracker/scs-backend:latest
    environment:
      ARANGO_HOSTS: cdev-arango-db-2:8529
      SCS_SHARD_ID: 102
      SCS_CLUSTER_MODEL: data/dolgoprudnii.yaml
      SCS_CLUSTER_POSITIONS: >-
        55.9263:37.7139 55.9330:37.7714 55.8888:37.7701
      SCS_CLUSTER_NAME: "Мытищи"
    ports:
      - "27021:8080"
    depends_on:
      - cdev-arango-db-2
    networks:
      cdev-network:

  cdev-backend-2-2:
    deploy:
      resources:
        limits:
          memory: 100M
    image: netcracker/scs-backend:latest
    environment:
      ARANGO_HOSTS: cdev-arango-db-2:8529
      SCS_SHARD_ID: 102
      SCS_CLUSTER_MODEL: data/dolgoprudnii.yaml
      SCS_CLUSTER_POSITIONS: >-
        55.9263:37.7139 55.9330:37.7714 55.8888:37.7701
      SCS_CLUSTER_NAME: "Мытищи"
    ports:
      - "27022:8080"
    depends_on:
      - cdev-arango-db-2
    networks:
      cdev-network:


  cdev-backend-3-1:
    deploy:
      resources:
        limits:
          memory: 100M
    image: netcracker/scs-backend:latest
    environment:
      ARANGO_HOSTS: cdev-arango-db-3:8529
      SCS_SHARD_ID: 103
      SCS_CLUSTER_MODEL: data/dolgoprudnii.yaml
      SCS_CLUSTER_POSITIONS: >-
        55.8084:37.3915 55.8666:37.3650 55.8273:37.2733
      SCS_CLUSTER_NAME: "Красногорск"
    ports:
      - "27031:8080"
    depends_on:
      - cdev-arango-db-3
    networks:
      cdev-network:

  cdev-backend-3-2:
    deploy:
      resources:
        limits:
          memory: 150M
    image: netcracker/scs-backend:latest
    environment:
      ARANGO_HOSTS: cdev-arango-db-3:8529
      SCS_SHARD_ID: 103
      SCS_CLUSTER_MODEL: data/dolgoprudnii.yaml
      SCS_CLUSTER_POSITIONS: >-
        55.8084:37.3915 55.8666:37.3650 55.8273:37.2733
      SCS_CLUSTER_NAME: "Красногорск"
    ports:
      - "27032:8080"
    depends_on:
      - cdev-arango-db-3
    networks:
      cdev-network:



  cdev-haproxy-1-1:
    deploy:
      resources:
        limits:
          memory: 50M
    image: netcracker/scs-backend-haproxy:latest
    environment:
      SCS_BACKENDS: cdev-backend-1-1 cdev-backend-1-2
      SCS_BACKEND_PORT: 8080
    ports:
      - "8081:8080"
    depends_on:
      - cdev-backend-1-1
      - cdev-backend-1-2
    networks:
      cdev-network:

  cdev-haproxy-1-2:
    deploy:
      resources:
        limits:
          memory: 50M
    image: netcracker/scs-backend-haproxy:latest
    environment:
      SCS_BACKENDS: cdev-backend-1-1 cdev-backend-1-2
      SCS_BACKEND_PORT: 8080
    ports:
      - "8082:8080"
    networks:
      cdev-network:
    depends_on:
      - cdev-backend-1-1
      - cdev-backend-1-2


  cdev-haproxy-2-1:
    deploy:
      resources:
        limits:
          memory: 50M
    image: netcracker/scs-backend-haproxy:latest
    environment:
      SCS_BACKENDS: cdev-backend-2-1 cdev-backend-2-2
      SCS_BACKEND_PORT: 8080
    ports:
      - "8083:8080"
    depends_on:
      - cdev-backend-2-1
      - cdev-backend-2-2
    networks:
      cdev-network:

  cdev-haproxy-2-2:
    deploy:
      resources:
        limits:
          memory: 50M
    image: netcracker/scs-backend-haproxy:latest
    environment:
      SCS_BACKENDS: cdev-backend-2-1 cdev-backend-2-2
      SCS_BACKEND_PORT: 8080
    ports:
      - "8084:8080"
    networks:
      cdev-network:
    depends_on:
      - cdev-backend-2-1
      - cdev-backend-2-2


  cdev-haproxy-3-1:
    deploy:
      resources:
        limits:
          memory: 50M
    image: netcracker/scs-backend-haproxy:latest
    environment:
      SCS_BACKENDS: cdev-backend-3-1 cdev-backend-3-2
      SCS_BACKEND_PORT: 8080
    ports:
      - "8085:8080"
    depends_on:
      - cdev-backend-3-1
      - cdev-backend-3-2
    networks:
      cdev-network:

  cdev-haproxy-3-2:
    deploy:
      resources:
        limits:
          memory: 50M
    image: netcracker/scs-backend-haproxy:latest
    environment:
      SCS_BACKENDS: cdev-backend-3-1 cdev-backend-3-2
      SCS_BACKEND_PORT: 8080
    ports:
      - "8086:8080"
    networks:
      cdev-network:
    depends_on:
      - cdev-backend-3-1
      - cdev-backend-3-2



  cdev-coordinator:
    deploy:
      resources:
        limits:
          memory: 100M
    image: netcracker/scs-coordinator:latest
    environment:
      SCS_COORDINATOR_BACKENDS: "cdev-haproxy-1-1:8080|cdev-haproxy-1-2:8080 cdev-haproxy-2-1:8080|cdev-haproxy-2-2:8080 cdev-haproxy-3-1:8080|cdev-haproxy-3-2:8080"
    ports:
      - "27066:8080"
    depends_on:
      - cdev-haproxy-1-1
      - cdev-haproxy-1-2
      - cdev-haproxy-2-1
      - cdev-haproxy-2-2
      - cdev-haproxy-3-1
      - cdev-haproxy-3-2
    networks:
      cdev-network:



  cdev-client:
    deploy:
      resources:
        limits:
          memory: 100M
    image: netcracker/scs-client:latest
    environment:
      SCS_COORDINATOR_PROTOCOL: "http"
      SCS_COORDINATOR_HOST: "localhost"
      SCS_COORDINATOR_PORT: "27066"
    ports:
      - "27077:80"
    depends_on:
      - cdev-coordinator
    networks:
      cdev-network:

networks:
  cdev-network:

volumes:
  arangodb_data_container_1:
  arangodb_apps_data_container_1:
  arangodb_data_container_2:
  arangodb_apps_data_container_2:
  arangodb_data_container_3:
  arangodb_apps_data_container_3:
